### ISSUE TITLE
Save the learning session

### ISSUE THREAD

**Issue by talvasconcelos** [TravCav/AdaBoost#1]
Is there a way to store on file (json, js) the learned set?

Regards,
Tiago

**Comment by TravCav** [comment]
Something like this?
You'll need 
    var fs = require('fs');

After training you can dump the trainedLearners like so.
    fs.writeFileSync("learners.json", JSON.stringify(adaBoost.trainedLearners) );

 You can feed data into trainedLearners, but the constructor still wants to train on something. You can just feed in empty data. Then read in a file.
     var adaBoost = new AdaBoost([[""]],"");
     adaBoost.trainedLearners = JSON.parse(fs.readFileSync("learners.json", "utf8"));

Any specific requirements or feature ideas?

**Comment by talvasconcelos** [comment]
I guessed it was something along those lines... saving the learners!!
Thanks alot.

> Any specific requirements or feature ideas?
Let me use it and test it for a while and i'll get back to you with some feedback. I was researching on how to use it with an LSTM but haven't got to any conclusion yet!

BTW, is it possible for the AdaBoost to make a non binary prediction? I want to predict 1 of 3 outcomes on from the inputs. Right now i'm doing 2 training sessions for Output A and Output B, then if none of them predict 1 i default to Output C.

**Comment by TravCav** [comment]
For MultiClass Classification you'd have to train an instance for each outcome. A or not A. B or not B. C or not C.  Then compare which instance had the highest vote.
